using System.Diagnostics.CodeAnalysis;

namespace Photography.Management.Suite.Core.Contracts.CodeTypes;

public sealed record SedcardType : IDisposable
{
   public Guid SystemId { get; set; }

   public int Id { get; set; }

   public string Title { get; set; } = string.Empty;

   public bool IsActive { get; set; }

   public SedcardType()
   {
      
   }

   #region IDisposable Interface Implementation

   private bool disposed;

   /// <summary>
   /// Performs application-defined tasks associated with freeing, releasing, or resetting unmanaged resources.
   /// </summary>
   /// <autogeneratedoc />
   [ExcludeFromCodeCoverage]
   public void Dispose()
   {
      this.Dispose(true);
      GC.SuppressFinalize(this);
   }

   /// <summary>
   /// Releases unmanaged and - optionally - managed resources.
   /// </summary>
   /// <param name="disposing"><c>true</c> to release both managed and unmanaged resources; <c>false</c> to release only unmanaged resources.</param>
   /// <autogeneratedoc />
   [ExcludeFromCodeCoverage]
   private void Dispose(bool disposing)
   {
      if (!this.disposed && disposing)
      {
         // Disposing Logic
      }

      this.disposed = true;
   }

   /// <summary>
   /// Finalizes an instance of the <see cref="SedcardType"/> class.
   /// </summary>
   /// <autogeneratedoc />
   [ExcludeFromCodeCoverage]
   ~SedcardType()
   {
      this.Dispose(false);
   }

   #endregion
}
